extend type Mutation {
  """
  ✨ Insert a single `CostRecord` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  costRecord_insert(
    """
    Data object to insert into the table.
    """
    data: CostRecord_Data!
  ): CostRecord_KeyOutput! @fdc_generated(from: "CostRecord", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CropStageEvent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cropStageEvent_insert(
    """
    Data object to insert into the table.
    """
    data: CropStageEvent_Data!
  ): CropStageEvent_KeyOutput! @fdc_generated(from: "CropStageEvent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CropType` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cropType_insert(
    """
    Data object to insert into the table.
    """
    data: CropType_Data!
  ): CropType_KeyOutput! @fdc_generated(from: "CropType", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CropVariety` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cropVariety_insert(
    """
    Data object to insert into the table.
    """
    data: CropVariety_Data!
  ): CropVariety_KeyOutput! @fdc_generated(from: "CropVariety", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `CultivationCycle` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cultivationCycle_insert(
    """
    Data object to insert into the table.
    """
    data: CultivationCycle_Data!
  ): CultivationCycle_KeyOutput! @fdc_generated(from: "CultivationCycle", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DailyHouseReport` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  dailyHouseReport_insert(
    """
    Data object to insert into the table.
    """
    data: DailyHouseReport_Data!
  ): DailyHouseReport_KeyOutput! @fdc_generated(from: "DailyHouseReport", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DiseasePestIncident` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  diseasePestIncident_insert(
    """
    Data object to insert into the table.
    """
    data: DiseasePestIncident_Data!
  ): DiseasePestIncident_KeyOutput! @fdc_generated(from: "DiseasePestIncident", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Farm` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  farm_insert(
    """
    Data object to insert into the table.
    """
    data: Farm_Data!
  ): Farm_KeyOutput! @fdc_generated(from: "Farm", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `FertilizationLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  fertilizationLog_insert(
    """
    Data object to insert into the table.
    """
    data: FertilizationLog_Data!
  ): FertilizationLog_KeyOutput! @fdc_generated(from: "FertilizationLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Greenhouse` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  greenhouse_insert(
    """
    Data object to insert into the table.
    """
    data: Greenhouse_Data!
  ): Greenhouse_KeyOutput! @fdc_generated(from: "Greenhouse", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `GreenhouseEnvironmentLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  greenhouseEnvironmentLog_insert(
    """
    Data object to insert into the table.
    """
    data: GreenhouseEnvironmentLog_Data!
  ): GreenhouseEnvironmentLog_KeyOutput! @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `GrowthConditionLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  growthConditionLog_insert(
    """
    Data object to insert into the table.
    """
    data: GrowthConditionLog_Data!
  ): GrowthConditionLog_KeyOutput! @fdc_generated(from: "GrowthConditionLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `HarvestRecord` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  harvestRecord_insert(
    """
    Data object to insert into the table.
    """
    data: HarvestRecord_Data!
  ): HarvestRecord_KeyOutput! @fdc_generated(from: "HarvestRecord", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `IrrigationLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  irrigationLog_insert(
    """
    Data object to insert into the table.
    """
    data: IrrigationLog_Data!
  ): IrrigationLog_KeyOutput! @fdc_generated(from: "IrrigationLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `LaborLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  laborLog_insert(
    """
    Data object to insert into the table.
    """
    data: LaborLog_Data!
  ): LaborLog_KeyOutput! @fdc_generated(from: "LaborLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Organization` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organization_insert(
    """
    Data object to insert into the table.
    """
    data: Organization_Data!
  ): Organization_KeyOutput! @fdc_generated(from: "Organization", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `OrganizationMember` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organizationMember_insert(
    """
    Data object to insert into the table.
    """
    data: OrganizationMember_Data!
  ): OrganizationMember_KeyOutput! @fdc_generated(from: "OrganizationMember", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PesticideLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  pesticideLog_insert(
    """
    Data object to insert into the table.
    """
    data: PesticideLog_Data!
  ): PesticideLog_KeyOutput! @fdc_generated(from: "PesticideLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ShipmentRecord` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  shipmentRecord_insert(
    """
    Data object to insert into the table.
    """
    data: ShipmentRecord_Data!
  ): ShipmentRecord_KeyOutput! @fdc_generated(from: "ShipmentRecord", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StrawberryGrowthLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  strawberryGrowthLog_insert(
    """
    Data object to insert into the table.
    """
    data: StrawberryGrowthLog_Data!
  ): StrawberryGrowthLog_KeyOutput! @fdc_generated(from: "StrawberryGrowthLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WeatherDaily` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  weatherDaily_insert(
    """
    Data object to insert into the table.
    """
    data: WeatherDaily_Data!
  ): WeatherDaily_KeyOutput! @fdc_generated(from: "WeatherDaily", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WorkLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workLog_insert(
    """
    Data object to insert into the table.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput! @fdc_generated(from: "WorkLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert `CostRecord` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  costRecord_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CostRecord_Data!]!
  ): [CostRecord_KeyOutput!]! @fdc_generated(from: "CostRecord", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CropStageEvent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cropStageEvent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CropStageEvent_Data!]!
  ): [CropStageEvent_KeyOutput!]! @fdc_generated(from: "CropStageEvent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CropType` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cropType_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CropType_Data!]!
  ): [CropType_KeyOutput!]! @fdc_generated(from: "CropType", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CropVariety` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cropVariety_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CropVariety_Data!]!
  ): [CropVariety_KeyOutput!]! @fdc_generated(from: "CropVariety", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `CultivationCycle` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  cultivationCycle_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CultivationCycle_Data!]!
  ): [CultivationCycle_KeyOutput!]! @fdc_generated(from: "CultivationCycle", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DailyHouseReport` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  dailyHouseReport_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DailyHouseReport_Data!]!
  ): [DailyHouseReport_KeyOutput!]! @fdc_generated(from: "DailyHouseReport", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DiseasePestIncident` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  diseasePestIncident_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DiseasePestIncident_Data!]!
  ): [DiseasePestIncident_KeyOutput!]! @fdc_generated(from: "DiseasePestIncident", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Farm` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  farm_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Farm_Data!]!
  ): [Farm_KeyOutput!]! @fdc_generated(from: "Farm", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `FertilizationLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  fertilizationLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [FertilizationLog_Data!]!
  ): [FertilizationLog_KeyOutput!]! @fdc_generated(from: "FertilizationLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Greenhouse` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  greenhouse_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Greenhouse_Data!]!
  ): [Greenhouse_KeyOutput!]! @fdc_generated(from: "Greenhouse", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `GreenhouseEnvironmentLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  greenhouseEnvironmentLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [GreenhouseEnvironmentLog_Data!]!
  ): [GreenhouseEnvironmentLog_KeyOutput!]! @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `GrowthConditionLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  growthConditionLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [GrowthConditionLog_Data!]!
  ): [GrowthConditionLog_KeyOutput!]! @fdc_generated(from: "GrowthConditionLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `HarvestRecord` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  harvestRecord_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [HarvestRecord_Data!]!
  ): [HarvestRecord_KeyOutput!]! @fdc_generated(from: "HarvestRecord", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `IrrigationLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  irrigationLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [IrrigationLog_Data!]!
  ): [IrrigationLog_KeyOutput!]! @fdc_generated(from: "IrrigationLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `LaborLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  laborLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LaborLog_Data!]!
  ): [LaborLog_KeyOutput!]! @fdc_generated(from: "LaborLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Organization` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organization_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Organization_Data!]!
  ): [Organization_KeyOutput!]! @fdc_generated(from: "Organization", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `OrganizationMember` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  organizationMember_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [OrganizationMember_Data!]!
  ): [OrganizationMember_KeyOutput!]! @fdc_generated(from: "OrganizationMember", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PesticideLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  pesticideLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PesticideLog_Data!]!
  ): [PesticideLog_KeyOutput!]! @fdc_generated(from: "PesticideLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ShipmentRecord` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  shipmentRecord_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ShipmentRecord_Data!]!
  ): [ShipmentRecord_KeyOutput!]! @fdc_generated(from: "ShipmentRecord", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StrawberryGrowthLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  strawberryGrowthLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StrawberryGrowthLog_Data!]!
  ): [StrawberryGrowthLog_KeyOutput!]! @fdc_generated(from: "StrawberryGrowthLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WeatherDaily` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  weatherDaily_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WeatherDaily_Data!]!
  ): [WeatherDaily_KeyOutput!]! @fdc_generated(from: "WeatherDaily", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WorkLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  workLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WorkLog_Data!]!
  ): [WorkLog_KeyOutput!]! @fdc_generated(from: "WorkLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `CostRecord` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CostRecord`.
  """
  costRecord_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CostRecord_Data!
  ): CostRecord_KeyOutput! @fdc_generated(from: "CostRecord", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CropStageEvent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CropStageEvent`.
  """
  cropStageEvent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CropStageEvent_Data!
  ): CropStageEvent_KeyOutput! @fdc_generated(from: "CropStageEvent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CropType` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CropType`.
  """
  cropType_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CropType_Data!
  ): CropType_KeyOutput! @fdc_generated(from: "CropType", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CropVariety` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CropVariety`.
  """
  cropVariety_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CropVariety_Data!
  ): CropVariety_KeyOutput! @fdc_generated(from: "CropVariety", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `CultivationCycle` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CultivationCycle`.
  """
  cultivationCycle_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CultivationCycle_Data!
  ): CultivationCycle_KeyOutput! @fdc_generated(from: "CultivationCycle", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DailyHouseReport` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DailyHouseReport`.
  """
  dailyHouseReport_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DailyHouseReport_Data!
  ): DailyHouseReport_KeyOutput! @fdc_generated(from: "DailyHouseReport", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DiseasePestIncident` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DiseasePestIncident`.
  """
  diseasePestIncident_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DiseasePestIncident_Data!
  ): DiseasePestIncident_KeyOutput! @fdc_generated(from: "DiseasePestIncident", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Farm` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Farm`.
  """
  farm_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Farm_Data!
  ): Farm_KeyOutput! @fdc_generated(from: "Farm", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `FertilizationLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FertilizationLog`.
  """
  fertilizationLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: FertilizationLog_Data!
  ): FertilizationLog_KeyOutput! @fdc_generated(from: "FertilizationLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Greenhouse` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Greenhouse`.
  """
  greenhouse_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Greenhouse_Data!
  ): Greenhouse_KeyOutput! @fdc_generated(from: "Greenhouse", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `GreenhouseEnvironmentLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GreenhouseEnvironmentLog`.
  """
  greenhouseEnvironmentLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: GreenhouseEnvironmentLog_Data!
  ): GreenhouseEnvironmentLog_KeyOutput! @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `GrowthConditionLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GrowthConditionLog`.
  """
  growthConditionLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: GrowthConditionLog_Data!
  ): GrowthConditionLog_KeyOutput! @fdc_generated(from: "GrowthConditionLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `HarvestRecord` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `HarvestRecord`.
  """
  harvestRecord_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: HarvestRecord_Data!
  ): HarvestRecord_KeyOutput! @fdc_generated(from: "HarvestRecord", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `IrrigationLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `IrrigationLog`.
  """
  irrigationLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: IrrigationLog_Data!
  ): IrrigationLog_KeyOutput! @fdc_generated(from: "IrrigationLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `LaborLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LaborLog`.
  """
  laborLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LaborLog_Data!
  ): LaborLog_KeyOutput! @fdc_generated(from: "LaborLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Organization` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Organization`.
  """
  organization_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Organization_Data!
  ): Organization_KeyOutput! @fdc_generated(from: "Organization", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `OrganizationMember` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `OrganizationMember`.
  """
  organizationMember_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: OrganizationMember_Data!
  ): OrganizationMember_KeyOutput! @fdc_generated(from: "OrganizationMember", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PesticideLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PesticideLog`.
  """
  pesticideLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PesticideLog_Data!
  ): PesticideLog_KeyOutput! @fdc_generated(from: "PesticideLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ShipmentRecord` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ShipmentRecord`.
  """
  shipmentRecord_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ShipmentRecord_Data!
  ): ShipmentRecord_KeyOutput! @fdc_generated(from: "ShipmentRecord", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StrawberryGrowthLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StrawberryGrowthLog`.
  """
  strawberryGrowthLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StrawberryGrowthLog_Data!
  ): StrawberryGrowthLog_KeyOutput! @fdc_generated(from: "StrawberryGrowthLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WeatherDaily` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WeatherDaily`.
  """
  weatherDaily_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WeatherDaily_Data!
  ): WeatherDaily_KeyOutput! @fdc_generated(from: "WeatherDaily", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WorkLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkLog`.
  """
  workLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput! @fdc_generated(from: "WorkLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `CostRecord` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CostRecord`.
  """
  costRecord_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CostRecord_Data!]!
  ): [CostRecord_KeyOutput!]! @fdc_generated(from: "CostRecord", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CropStageEvent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CropStageEvent`.
  """
  cropStageEvent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CropStageEvent_Data!]!
  ): [CropStageEvent_KeyOutput!]! @fdc_generated(from: "CropStageEvent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CropType` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CropType`.
  """
  cropType_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CropType_Data!]!
  ): [CropType_KeyOutput!]! @fdc_generated(from: "CropType", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CropVariety` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CropVariety`.
  """
  cropVariety_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CropVariety_Data!]!
  ): [CropVariety_KeyOutput!]! @fdc_generated(from: "CropVariety", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `CultivationCycle` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CultivationCycle`.
  """
  cultivationCycle_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CultivationCycle_Data!]!
  ): [CultivationCycle_KeyOutput!]! @fdc_generated(from: "CultivationCycle", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DailyHouseReport` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DailyHouseReport`.
  """
  dailyHouseReport_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DailyHouseReport_Data!]!
  ): [DailyHouseReport_KeyOutput!]! @fdc_generated(from: "DailyHouseReport", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DiseasePestIncident` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DiseasePestIncident`.
  """
  diseasePestIncident_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DiseasePestIncident_Data!]!
  ): [DiseasePestIncident_KeyOutput!]! @fdc_generated(from: "DiseasePestIncident", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Farm` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Farm`.
  """
  farm_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Farm_Data!]!
  ): [Farm_KeyOutput!]! @fdc_generated(from: "Farm", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `FertilizationLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `FertilizationLog`.
  """
  fertilizationLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [FertilizationLog_Data!]!
  ): [FertilizationLog_KeyOutput!]! @fdc_generated(from: "FertilizationLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Greenhouse` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Greenhouse`.
  """
  greenhouse_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Greenhouse_Data!]!
  ): [Greenhouse_KeyOutput!]! @fdc_generated(from: "Greenhouse", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `GreenhouseEnvironmentLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GreenhouseEnvironmentLog`.
  """
  greenhouseEnvironmentLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [GreenhouseEnvironmentLog_Data!]!
  ): [GreenhouseEnvironmentLog_KeyOutput!]! @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `GrowthConditionLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `GrowthConditionLog`.
  """
  growthConditionLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [GrowthConditionLog_Data!]!
  ): [GrowthConditionLog_KeyOutput!]! @fdc_generated(from: "GrowthConditionLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `HarvestRecord` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `HarvestRecord`.
  """
  harvestRecord_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [HarvestRecord_Data!]!
  ): [HarvestRecord_KeyOutput!]! @fdc_generated(from: "HarvestRecord", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `IrrigationLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `IrrigationLog`.
  """
  irrigationLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [IrrigationLog_Data!]!
  ): [IrrigationLog_KeyOutput!]! @fdc_generated(from: "IrrigationLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `LaborLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LaborLog`.
  """
  laborLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LaborLog_Data!]!
  ): [LaborLog_KeyOutput!]! @fdc_generated(from: "LaborLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Organization` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Organization`.
  """
  organization_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Organization_Data!]!
  ): [Organization_KeyOutput!]! @fdc_generated(from: "Organization", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `OrganizationMember` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `OrganizationMember`.
  """
  organizationMember_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [OrganizationMember_Data!]!
  ): [OrganizationMember_KeyOutput!]! @fdc_generated(from: "OrganizationMember", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PesticideLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PesticideLog`.
  """
  pesticideLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PesticideLog_Data!]!
  ): [PesticideLog_KeyOutput!]! @fdc_generated(from: "PesticideLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ShipmentRecord` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ShipmentRecord`.
  """
  shipmentRecord_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ShipmentRecord_Data!]!
  ): [ShipmentRecord_KeyOutput!]! @fdc_generated(from: "ShipmentRecord", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StrawberryGrowthLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StrawberryGrowthLog`.
  """
  strawberryGrowthLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StrawberryGrowthLog_Data!]!
  ): [StrawberryGrowthLog_KeyOutput!]! @fdc_generated(from: "StrawberryGrowthLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WeatherDaily` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WeatherDaily`.
  """
  weatherDaily_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WeatherDaily_Data!]!
  ): [WeatherDaily_KeyOutput!]! @fdc_generated(from: "WeatherDaily", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WorkLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorkLog`.
  """
  workLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WorkLog_Data!]!
  ): [WorkLog_KeyOutput!]! @fdc_generated(from: "WorkLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `CostRecord` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CostRecord` or `null` if not found.
  """
  costRecord_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CostRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CostRecord_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CostRecord_Data!
  ): CostRecord_KeyOutput @fdc_generated(from: "CostRecord", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CropStageEvent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CropStageEvent` or `null` if not found.
  """
  cropStageEvent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropStageEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropStageEvent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CropStageEvent_Data!
  ): CropStageEvent_KeyOutput @fdc_generated(from: "CropStageEvent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CropType` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CropType` or `null` if not found.
  """
  cropType_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropType_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CropType_Data!
  ): CropType_KeyOutput @fdc_generated(from: "CropType", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CropVariety` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CropVariety` or `null` if not found.
  """
  cropVariety_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropVariety_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropVariety_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CropVariety_Data!
  ): CropVariety_KeyOutput @fdc_generated(from: "CropVariety", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `CultivationCycle` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CultivationCycle` or `null` if not found.
  """
  cultivationCycle_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CultivationCycle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CultivationCycle_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CultivationCycle_Data!
  ): CultivationCycle_KeyOutput @fdc_generated(from: "CultivationCycle", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DailyHouseReport` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DailyHouseReport` or `null` if not found.
  """
  dailyHouseReport_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyHouseReport_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyHouseReport_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DailyHouseReport_Data!
  ): DailyHouseReport_KeyOutput @fdc_generated(from: "DailyHouseReport", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DiseasePestIncident` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DiseasePestIncident` or `null` if not found.
  """
  diseasePestIncident_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DiseasePestIncident_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DiseasePestIncident_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DiseasePestIncident_Data!
  ): DiseasePestIncident_KeyOutput @fdc_generated(from: "DiseasePestIncident", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Farm` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Farm` or `null` if not found.
  """
  farm_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Farm_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Farm_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Farm_Data!
  ): Farm_KeyOutput @fdc_generated(from: "Farm", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `FertilizationLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `FertilizationLog` or `null` if not found.
  """
  fertilizationLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FertilizationLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FertilizationLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: FertilizationLog_Data!
  ): FertilizationLog_KeyOutput @fdc_generated(from: "FertilizationLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Greenhouse` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Greenhouse` or `null` if not found.
  """
  greenhouse_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Greenhouse_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Greenhouse_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Greenhouse_Data!
  ): Greenhouse_KeyOutput @fdc_generated(from: "Greenhouse", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `GreenhouseEnvironmentLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `GreenhouseEnvironmentLog` or `null` if not found.
  """
  greenhouseEnvironmentLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GreenhouseEnvironmentLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GreenhouseEnvironmentLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: GreenhouseEnvironmentLog_Data!
  ): GreenhouseEnvironmentLog_KeyOutput @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `GrowthConditionLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `GrowthConditionLog` or `null` if not found.
  """
  growthConditionLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GrowthConditionLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GrowthConditionLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: GrowthConditionLog_Data!
  ): GrowthConditionLog_KeyOutput @fdc_generated(from: "GrowthConditionLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `HarvestRecord` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `HarvestRecord` or `null` if not found.
  """
  harvestRecord_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: HarvestRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: HarvestRecord_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: HarvestRecord_Data!
  ): HarvestRecord_KeyOutput @fdc_generated(from: "HarvestRecord", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `IrrigationLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `IrrigationLog` or `null` if not found.
  """
  irrigationLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: IrrigationLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: IrrigationLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: IrrigationLog_Data!
  ): IrrigationLog_KeyOutput @fdc_generated(from: "IrrigationLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `LaborLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LaborLog` or `null` if not found.
  """
  laborLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LaborLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LaborLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LaborLog_Data!
  ): LaborLog_KeyOutput @fdc_generated(from: "LaborLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Organization` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Organization` or `null` if not found.
  """
  organization_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Organization_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Organization_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Organization_Data!
  ): Organization_KeyOutput @fdc_generated(from: "Organization", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `OrganizationMember` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `OrganizationMember` or `null` if not found.
  """
  organizationMember_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OrganizationMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OrganizationMember_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: OrganizationMember_Data!
  ): OrganizationMember_KeyOutput @fdc_generated(from: "OrganizationMember", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PesticideLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PesticideLog` or `null` if not found.
  """
  pesticideLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PesticideLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PesticideLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PesticideLog_Data!
  ): PesticideLog_KeyOutput @fdc_generated(from: "PesticideLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ShipmentRecord` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ShipmentRecord` or `null` if not found.
  """
  shipmentRecord_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ShipmentRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ShipmentRecord_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ShipmentRecord_Data!
  ): ShipmentRecord_KeyOutput @fdc_generated(from: "ShipmentRecord", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StrawberryGrowthLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StrawberryGrowthLog` or `null` if not found.
  """
  strawberryGrowthLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StrawberryGrowthLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StrawberryGrowthLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StrawberryGrowthLog_Data!
  ): StrawberryGrowthLog_KeyOutput @fdc_generated(from: "StrawberryGrowthLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WeatherDaily` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WeatherDaily` or `null` if not found.
  """
  weatherDaily_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WeatherDaily_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WeatherDaily_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WeatherDaily_Data!
  ): WeatherDaily_KeyOutput @fdc_generated(from: "WeatherDaily", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WorkLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WorkLog` or `null` if not found.
  """
  workLog_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WorkLog_Data!
  ): WorkLog_KeyOutput @fdc_generated(from: "WorkLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update `CostRecord` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  costRecord_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CostRecord_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CostRecord_Data!
  ): Int! @fdc_generated(from: "CostRecord", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CropStageEvent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  cropStageEvent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CropStageEvent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CropStageEvent_Data!
  ): Int! @fdc_generated(from: "CropStageEvent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CropType` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  cropType_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CropType_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CropType_Data!
  ): Int! @fdc_generated(from: "CropType", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CropVariety` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  cropVariety_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CropVariety_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CropVariety_Data!
  ): Int! @fdc_generated(from: "CropVariety", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `CultivationCycle` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  cultivationCycle_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CultivationCycle_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CultivationCycle_Data!
  ): Int! @fdc_generated(from: "CultivationCycle", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DailyHouseReport` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  dailyHouseReport_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DailyHouseReport_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DailyHouseReport_Data!
  ): Int! @fdc_generated(from: "DailyHouseReport", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DiseasePestIncident` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  diseasePestIncident_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DiseasePestIncident_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DiseasePestIncident_Data!
  ): Int! @fdc_generated(from: "DiseasePestIncident", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Farm` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  farm_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Farm_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Farm_Data!
  ): Int! @fdc_generated(from: "Farm", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `FertilizationLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  fertilizationLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: FertilizationLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: FertilizationLog_Data!
  ): Int! @fdc_generated(from: "FertilizationLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Greenhouse` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  greenhouse_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Greenhouse_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Greenhouse_Data!
  ): Int! @fdc_generated(from: "Greenhouse", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `GreenhouseEnvironmentLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  greenhouseEnvironmentLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: GreenhouseEnvironmentLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: GreenhouseEnvironmentLog_Data!
  ): Int! @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `GrowthConditionLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  growthConditionLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: GrowthConditionLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: GrowthConditionLog_Data!
  ): Int! @fdc_generated(from: "GrowthConditionLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `HarvestRecord` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  harvestRecord_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: HarvestRecord_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: HarvestRecord_Data!
  ): Int! @fdc_generated(from: "HarvestRecord", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `IrrigationLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  irrigationLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: IrrigationLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: IrrigationLog_Data!
  ): Int! @fdc_generated(from: "IrrigationLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `LaborLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  laborLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LaborLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LaborLog_Data!
  ): Int! @fdc_generated(from: "LaborLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Organization` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  organization_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Organization_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Organization_Data!
  ): Int! @fdc_generated(from: "Organization", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `OrganizationMember` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  organizationMember_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: OrganizationMember_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: OrganizationMember_Data!
  ): Int! @fdc_generated(from: "OrganizationMember", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PesticideLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  pesticideLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PesticideLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PesticideLog_Data!
  ): Int! @fdc_generated(from: "PesticideLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ShipmentRecord` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  shipmentRecord_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ShipmentRecord_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ShipmentRecord_Data!
  ): Int! @fdc_generated(from: "ShipmentRecord", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StrawberryGrowthLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  strawberryGrowthLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StrawberryGrowthLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StrawberryGrowthLog_Data!
  ): Int! @fdc_generated(from: "StrawberryGrowthLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WeatherDaily` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  weatherDaily_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WeatherDaily_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WeatherDaily_Data!
  ): Int! @fdc_generated(from: "WeatherDaily", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WorkLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  workLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WorkLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WorkLog_Data!
  ): Int! @fdc_generated(from: "WorkLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `CostRecord` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  costRecord_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CostRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CostRecord_FirstRow
  ): CostRecord_KeyOutput @fdc_generated(from: "CostRecord", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CropStageEvent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  cropStageEvent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropStageEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropStageEvent_FirstRow
  ): CropStageEvent_KeyOutput @fdc_generated(from: "CropStageEvent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CropType` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  cropType_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropType_FirstRow
  ): CropType_KeyOutput @fdc_generated(from: "CropType", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CropVariety` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  cropVariety_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropVariety_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropVariety_FirstRow
  ): CropVariety_KeyOutput @fdc_generated(from: "CropVariety", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `CultivationCycle` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  cultivationCycle_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CultivationCycle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CultivationCycle_FirstRow
  ): CultivationCycle_KeyOutput @fdc_generated(from: "CultivationCycle", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DailyHouseReport` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  dailyHouseReport_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyHouseReport_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyHouseReport_FirstRow
  ): DailyHouseReport_KeyOutput @fdc_generated(from: "DailyHouseReport", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DiseasePestIncident` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  diseasePestIncident_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DiseasePestIncident_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DiseasePestIncident_FirstRow
  ): DiseasePestIncident_KeyOutput @fdc_generated(from: "DiseasePestIncident", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Farm` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  farm_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Farm_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Farm_FirstRow
  ): Farm_KeyOutput @fdc_generated(from: "Farm", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `FertilizationLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  fertilizationLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FertilizationLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FertilizationLog_FirstRow
  ): FertilizationLog_KeyOutput @fdc_generated(from: "FertilizationLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Greenhouse` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  greenhouse_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Greenhouse_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Greenhouse_FirstRow
  ): Greenhouse_KeyOutput @fdc_generated(from: "Greenhouse", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `GreenhouseEnvironmentLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  greenhouseEnvironmentLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GreenhouseEnvironmentLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GreenhouseEnvironmentLog_FirstRow
  ): GreenhouseEnvironmentLog_KeyOutput @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `GrowthConditionLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  growthConditionLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GrowthConditionLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GrowthConditionLog_FirstRow
  ): GrowthConditionLog_KeyOutput @fdc_generated(from: "GrowthConditionLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `HarvestRecord` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  harvestRecord_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: HarvestRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: HarvestRecord_FirstRow
  ): HarvestRecord_KeyOutput @fdc_generated(from: "HarvestRecord", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `IrrigationLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  irrigationLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: IrrigationLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: IrrigationLog_FirstRow
  ): IrrigationLog_KeyOutput @fdc_generated(from: "IrrigationLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `LaborLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  laborLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LaborLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LaborLog_FirstRow
  ): LaborLog_KeyOutput @fdc_generated(from: "LaborLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Organization` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  organization_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Organization_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Organization_FirstRow
  ): Organization_KeyOutput @fdc_generated(from: "Organization", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `OrganizationMember` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  organizationMember_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OrganizationMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OrganizationMember_FirstRow
  ): OrganizationMember_KeyOutput @fdc_generated(from: "OrganizationMember", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PesticideLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  pesticideLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PesticideLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PesticideLog_FirstRow
  ): PesticideLog_KeyOutput @fdc_generated(from: "PesticideLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ShipmentRecord` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  shipmentRecord_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ShipmentRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ShipmentRecord_FirstRow
  ): ShipmentRecord_KeyOutput @fdc_generated(from: "ShipmentRecord", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StrawberryGrowthLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  strawberryGrowthLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StrawberryGrowthLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StrawberryGrowthLog_FirstRow
  ): StrawberryGrowthLog_KeyOutput @fdc_generated(from: "StrawberryGrowthLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WeatherDaily` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  weatherDaily_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WeatherDaily_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WeatherDaily_FirstRow
  ): WeatherDaily_KeyOutput @fdc_generated(from: "WeatherDaily", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WorkLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  workLog_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow
  ): WorkLog_KeyOutput @fdc_generated(from: "WorkLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete `CostRecord` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  costRecord_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CostRecord_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CostRecord", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CropStageEvent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  cropStageEvent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CropStageEvent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CropStageEvent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CropType` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  cropType_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CropType_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CropType", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CropVariety` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  cropVariety_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CropVariety_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CropVariety", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `CultivationCycle` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  cultivationCycle_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CultivationCycle_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CultivationCycle", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DailyHouseReport` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  dailyHouseReport_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DailyHouseReport_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DailyHouseReport", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DiseasePestIncident` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  diseasePestIncident_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DiseasePestIncident_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DiseasePestIncident", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Farm` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  farm_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Farm_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Farm", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `FertilizationLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  fertilizationLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: FertilizationLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "FertilizationLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Greenhouse` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  greenhouse_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Greenhouse_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Greenhouse", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `GreenhouseEnvironmentLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  greenhouseEnvironmentLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: GreenhouseEnvironmentLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `GrowthConditionLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  growthConditionLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: GrowthConditionLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "GrowthConditionLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `HarvestRecord` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  harvestRecord_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: HarvestRecord_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "HarvestRecord", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `IrrigationLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  irrigationLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: IrrigationLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "IrrigationLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `LaborLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  laborLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LaborLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LaborLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Organization` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  organization_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Organization_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Organization", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `OrganizationMember` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  organizationMember_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: OrganizationMember_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "OrganizationMember", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PesticideLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  pesticideLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PesticideLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PesticideLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ShipmentRecord` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  shipmentRecord_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ShipmentRecord_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ShipmentRecord", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StrawberryGrowthLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  strawberryGrowthLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StrawberryGrowthLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StrawberryGrowthLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WeatherDaily` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  weatherDaily_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WeatherDaily_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WeatherDaily", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WorkLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  workLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WorkLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WorkLog", purpose: DELETE_MULTIPLE)
}
