extend type Query {
  """
  ✨ Look up a single `CostRecord` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  costRecord(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CostRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CostRecord_FirstRow
  ): CostRecord @fdc_generated(from: "CostRecord", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `CropStageEvent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  cropStageEvent(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropStageEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropStageEvent_FirstRow
  ): CropStageEvent @fdc_generated(from: "CropStageEvent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `CropType` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  cropType(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropType_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropType_FirstRow
  ): CropType @fdc_generated(from: "CropType", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `CropVariety` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  cropVariety(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CropVariety_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CropVariety_FirstRow
  ): CropVariety @fdc_generated(from: "CropVariety", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `CultivationCycle` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  cultivationCycle(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CultivationCycle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CultivationCycle_FirstRow
  ): CultivationCycle @fdc_generated(from: "CultivationCycle", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DailyHouseReport` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dailyHouseReport(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyHouseReport_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyHouseReport_FirstRow
  ): DailyHouseReport @fdc_generated(from: "DailyHouseReport", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DiseasePestIncident` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  diseasePestIncident(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DiseasePestIncident_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DiseasePestIncident_FirstRow
  ): DiseasePestIncident @fdc_generated(from: "DiseasePestIncident", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Farm` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  farm(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Farm_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Farm_FirstRow
  ): Farm @fdc_generated(from: "Farm", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FertilizationLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  fertilizationLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: FertilizationLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FertilizationLog_FirstRow
  ): FertilizationLog @fdc_generated(from: "FertilizationLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Greenhouse` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  greenhouse(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Greenhouse_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Greenhouse_FirstRow
  ): Greenhouse @fdc_generated(from: "Greenhouse", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GreenhouseEnvironmentLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  greenhouseEnvironmentLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GreenhouseEnvironmentLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GreenhouseEnvironmentLog_FirstRow
  ): GreenhouseEnvironmentLog @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `GrowthConditionLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  growthConditionLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: GrowthConditionLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: GrowthConditionLog_FirstRow
  ): GrowthConditionLog @fdc_generated(from: "GrowthConditionLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `HarvestRecord` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  harvestRecord(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: HarvestRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: HarvestRecord_FirstRow
  ): HarvestRecord @fdc_generated(from: "HarvestRecord", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `IrrigationLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  irrigationLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: IrrigationLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: IrrigationLog_FirstRow
  ): IrrigationLog @fdc_generated(from: "IrrigationLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `LaborLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  laborLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LaborLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LaborLog_FirstRow
  ): LaborLog @fdc_generated(from: "LaborLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Organization` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  organization(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Organization_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Organization_FirstRow
  ): Organization @fdc_generated(from: "Organization", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `OrganizationMember` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  organizationMember(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OrganizationMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OrganizationMember_FirstRow
  ): OrganizationMember @fdc_generated(from: "OrganizationMember", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PesticideLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  pesticideLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PesticideLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PesticideLog_FirstRow
  ): PesticideLog @fdc_generated(from: "PesticideLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ShipmentRecord` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  shipmentRecord(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ShipmentRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ShipmentRecord_FirstRow
  ): ShipmentRecord @fdc_generated(from: "ShipmentRecord", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StrawberryGrowthLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  strawberryGrowthLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StrawberryGrowthLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StrawberryGrowthLog_FirstRow
  ): StrawberryGrowthLog @fdc_generated(from: "StrawberryGrowthLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WeatherDaily` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  weatherDaily(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WeatherDaily_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WeatherDaily_FirstRow
  ): WeatherDaily @fdc_generated(from: "WeatherDaily", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WorkLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  workLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorkLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorkLog_FirstRow
  ): WorkLog @fdc_generated(from: "WorkLog", purpose: QUERY_SINGLE)
  """
  ✨ List `CostRecord` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  costRecords(
    """
    Filter condition to narrow down the query results.
    """
    where: CostRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CostRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CostRecord_Having
  ): [CostRecord!]! @fdc_generated(from: "CostRecord", purpose: QUERY_MULTIPLE)
  """
  ✨ List `CropStageEvent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  cropStageEvents(
    """
    Filter condition to narrow down the query results.
    """
    where: CropStageEvent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CropStageEvent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CropStageEvent_Having
  ): [CropStageEvent!]! @fdc_generated(from: "CropStageEvent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `CropType` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  cropTypes(
    """
    Filter condition to narrow down the query results.
    """
    where: CropType_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CropType_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CropType_Having
  ): [CropType!]! @fdc_generated(from: "CropType", purpose: QUERY_MULTIPLE)
  """
  ✨ List `CropVariety` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  cropVarieties(
    """
    Filter condition to narrow down the query results.
    """
    where: CropVariety_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CropVariety_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CropVariety_Having
  ): [CropVariety!]! @fdc_generated(from: "CropVariety", purpose: QUERY_MULTIPLE)
  """
  ✨ List `CultivationCycle` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  cultivationCycles(
    """
    Filter condition to narrow down the query results.
    """
    where: CultivationCycle_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CultivationCycle_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CultivationCycle_Having
  ): [CultivationCycle!]! @fdc_generated(from: "CultivationCycle", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DailyHouseReport` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dailyHouseReports(
    """
    Filter condition to narrow down the query results.
    """
    where: DailyHouseReport_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DailyHouseReport_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DailyHouseReport_Having
  ): [DailyHouseReport!]! @fdc_generated(from: "DailyHouseReport", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DiseasePestIncident` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  diseasePestIncidents(
    """
    Filter condition to narrow down the query results.
    """
    where: DiseasePestIncident_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DiseasePestIncident_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DiseasePestIncident_Having
  ): [DiseasePestIncident!]! @fdc_generated(from: "DiseasePestIncident", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Farm` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  farms(
    """
    Filter condition to narrow down the query results.
    """
    where: Farm_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Farm_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Farm_Having
  ): [Farm!]! @fdc_generated(from: "Farm", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FertilizationLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  fertilizationLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: FertilizationLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FertilizationLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FertilizationLog_Having
  ): [FertilizationLog!]! @fdc_generated(from: "FertilizationLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Greenhouse` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  greenhouses(
    """
    Filter condition to narrow down the query results.
    """
    where: Greenhouse_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Greenhouse_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Greenhouse_Having
  ): [Greenhouse!]! @fdc_generated(from: "Greenhouse", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GreenhouseEnvironmentLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  greenhouseEnvironmentLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: GreenhouseEnvironmentLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GreenhouseEnvironmentLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GreenhouseEnvironmentLog_Having
  ): [GreenhouseEnvironmentLog!]! @fdc_generated(from: "GreenhouseEnvironmentLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `GrowthConditionLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  growthConditionLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: GrowthConditionLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [GrowthConditionLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: GrowthConditionLog_Having
  ): [GrowthConditionLog!]! @fdc_generated(from: "GrowthConditionLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `HarvestRecord` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  harvestRecords(
    """
    Filter condition to narrow down the query results.
    """
    where: HarvestRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [HarvestRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: HarvestRecord_Having
  ): [HarvestRecord!]! @fdc_generated(from: "HarvestRecord", purpose: QUERY_MULTIPLE)
  """
  ✨ List `IrrigationLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  irrigationLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: IrrigationLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [IrrigationLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: IrrigationLog_Having
  ): [IrrigationLog!]! @fdc_generated(from: "IrrigationLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `LaborLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  laborLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: LaborLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LaborLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LaborLog_Having
  ): [LaborLog!]! @fdc_generated(from: "LaborLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Organization` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  organizations(
    """
    Filter condition to narrow down the query results.
    """
    where: Organization_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Organization_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Organization_Having
  ): [Organization!]! @fdc_generated(from: "Organization", purpose: QUERY_MULTIPLE)
  """
  ✨ List `OrganizationMember` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  organizationMembers(
    """
    Filter condition to narrow down the query results.
    """
    where: OrganizationMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OrganizationMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OrganizationMember_Having
  ): [OrganizationMember!]! @fdc_generated(from: "OrganizationMember", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PesticideLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  pesticideLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: PesticideLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PesticideLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PesticideLog_Having
  ): [PesticideLog!]! @fdc_generated(from: "PesticideLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ShipmentRecord` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  shipmentRecords(
    """
    Filter condition to narrow down the query results.
    """
    where: ShipmentRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ShipmentRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ShipmentRecord_Having
  ): [ShipmentRecord!]! @fdc_generated(from: "ShipmentRecord", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StrawberryGrowthLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  strawberryGrowthLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: StrawberryGrowthLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StrawberryGrowthLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StrawberryGrowthLog_Having
  ): [StrawberryGrowthLog!]! @fdc_generated(from: "StrawberryGrowthLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WeatherDaily` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  weatherDailies(
    """
    Filter condition to narrow down the query results.
    """
    where: WeatherDaily_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WeatherDaily_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WeatherDaily_Having
  ): [WeatherDaily!]! @fdc_generated(from: "WeatherDaily", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WorkLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  workLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: WorkLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorkLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WorkLog_Having
  ): [WorkLog!]! @fdc_generated(from: "WorkLog", purpose: QUERY_MULTIPLE)
}
